/*
 * This document contains the data for each sucursal, on sale products and in stock products
 */

--sucursal 1
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,1,11);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,2,8);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,3,4);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,4,13);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,5,13);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,6,13);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,7,14);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,8,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,9,1);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,10,4);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,11,3);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,12,13);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,13,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,14,3);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,15,8);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,16,14);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,17,5);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,18,12);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,19,13);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,20,2);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,21,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,22,3);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,23,12);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,24,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,25,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,26,8);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,27,10);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,28,9);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,29,2);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,30,13);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,31,14);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,32,5);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,33,8);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,34,5);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,35,15);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,36,15);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,37,11);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,38,12);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,39,10);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,40,12);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,41,11);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,42,14);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,43,15);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,44,14);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,45,10);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,46,15);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,47,9);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,48,15);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,49,15);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,50,15);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,51,12);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,52,10);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,53,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,54,13);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,55,10);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,56,2);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,57,4);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,58,12);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,59,2);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,60,11);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,61,5);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,62,9);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,63,7);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,64,14);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,65,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,66,3);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,67,9);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,68,8);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,69,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,70,13);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,71,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,72,15);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,73,14);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,74,5);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,75,8);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,76,4);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,77,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,78,1);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,79,10);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,80,14);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,81,4);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,82,9);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,83,3);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,84,9);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,85,2);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,86,4);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,87,3);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,88,11);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,89,10);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,90,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,91,4);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,92,10);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,93,14);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,94,8);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,95,15);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,96,12);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,97,8);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,98,5);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,99,7);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (1,100,14);

INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,25,3,4);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,26,5,6);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,27,9,9);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,28,2,10);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,29,9,9);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,30,7,2);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,31,5,14);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,32,4,12);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,33,8,6);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,34,1,14);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,35,7,13);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,36,1,8);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,37,7,9);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,38,4,11);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,39,6,6);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,40,10,14);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,41,10,3);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,42,6,1);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,43,9,4);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,44,5,4);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,45,7,6);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,46,8,2);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,47,4,13);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,48,2,8);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,49,4,5);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,50,2,5);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,51,6,11);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,52,10,14);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,53,3,14);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,54,10,3);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,55,10,15);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,56,3,15);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,57,6,11);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,58,6,15);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,59,7,4);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,60,9,2);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,61,2,7);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,62,6,12);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,63,3,6);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,64,10,4);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,65,4,6);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,66,9,5);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,67,8,2);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,68,9,5);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,69,3,2);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,70,3,4);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,71,7,4);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,72,8,12);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,73,1,12);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (1,74,1,15);

--sucursal 2
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,101,9);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,102,4);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,103,13);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,104,4);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,105,15);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,106,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,107,4);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,108,3);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,109,10);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,110,1);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,111,15);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,112,13);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,113,1);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,114,8);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,115,2);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,116,2);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,117,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,118,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,119,11);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,120,15);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,121,7);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,122,5);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,123,2);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,124,13);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,125,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,126,7);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,127,1);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,128,2);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,129,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,130,2);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,131,10);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,132,15);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,133,10);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,134,11);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,135,7);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,136,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,137,14);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,138,9);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,139,13);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,140,10);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,141,8);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,142,11);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,143,15);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,144,1);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,145,4);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,146,14);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,147,12);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,148,8);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,149,9);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,150,7);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,151,4);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,152,2);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,153,11);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,154,7);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,155,9);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,156,8);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,157,13);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,158,5);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,159,5);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,160,3);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,161,5);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,162,4);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,163,11);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,164,14);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,165,7);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,166,9);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,167,5);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,168,7);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,169,8);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,170,2);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,171,8);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,172,4);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,173,9);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,174,10);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (2,175,1);

INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,150,4,2);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,151,6,5);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,152,5,5);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,153,4,12);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,154,4,11);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,155,1,9);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,156,7,12);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,157,2,9);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,158,4,1);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,159,2,4);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,160,5,1);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,161,4,4);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,162,9,7);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,163,10,1);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,164,4,15);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,165,4,12);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,166,2,1);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,167,1,10);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,168,3,14);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,169,4,9);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,170,5,14);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,171,5,15);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,172,6,6);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,173,6,15);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (2,174,9,9);


--sucursal 3
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,176,1);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,177,3);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,178,14);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,179,11);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,180,2);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,181,13);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,182,1);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,183,1);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,184,8);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,185,12);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,186,12);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,187,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,188,15);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,189,2);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,190,1);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,191,15);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,192,11);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,193,2);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,194,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,195,2);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,196,12);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,197,9);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,198,7);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,199,10);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,200,7);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,201,9);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,202,15);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,203,5);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,204,10);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,205,9);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,206,8);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,207,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,208,8);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,209,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,210,9);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,211,11);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,212,11);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,213,3);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,214,2);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,215,2);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,216,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,217,9);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,218,12);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,219,7);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,220,1);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,221,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,222,13);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,223,4);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,224,15);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,225,3);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,226,11);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,227,5);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,228,15);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,229,10);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,230,11);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,231,7);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,232,11);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,233,13);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,234,12);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,235,2);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,236,1);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,237,9);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,238,13);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,239,8);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,240,13);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,241,6);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,242,7);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,243,14);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,244,4);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,245,5);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,246,11);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,247,4);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,248,12);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,249,4);
INSERT INTO storage.on_sale(id_sucursal, id_product, existences) VALUES (3,250,10);

INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,176,6,2);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,177,2,11);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,178,3,13);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,179,4,7);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,180,9,4);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,181,10,2);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,182,1,6);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,183,3,5);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,184,6,6);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,185,2,11);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,186,1,12);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,187,9,6);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,188,2,15);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,189,10,5);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,190,3,8);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,191,10,8);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,192,10,7);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,193,7,6);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,194,10,8);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,195,10,2);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,196,7,14);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,197,4,10);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,198,2,5);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,199,3,7);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,200,1,6);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,201,9,9);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,202,2,13);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,203,10,6);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,204,1,9);
INSERT INTO storage.stock(id_sucursal, id_product, hall, existences) VALUES (3,205,6,8);

